# Generated by Django 3.1.2 on 2020-10-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201019_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pushups',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
