# Generated by Django 3.1.2 on 2020-10-19 05:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pushup', '0002_auto_20201019_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockvalue',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 19, 5, 53, 55, 274646, tzinfo=utc)),
        ),
    ]
