# Generated by Django 3.1.2 on 2020-10-19 05:56

from django.db import migrations, models
import pushup.models


class Migration(migrations.Migration):

    dependencies = [
        ('pushup', '0003_auto_20201019_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockvalue',
            name='time',
            field=models.DateTimeField(default=pushup.models.get_time),
        ),
    ]
